[package]
name = "lant"
version = "0.1.0"
edition = "2021"
authors = ["eyeori@icloud.com"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
base64 = "0.21.0"
bytes = "1.4.0"
chrono = "0.4.24"
crossbeam-channel = "0.5.7"
futures = "0.3.28"
getset = "0.1.2"
net2 = "0.2.38"
once_cell = "1.17.1"
path-absolutize = "3.0.14"
quinn = "0.9.3"
rcgen = "0.10.0"
rustls = { version = "0.20.8", features = ["quic"] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
structopt = { version = "0.3.26", features = ["paw"] }
tokio = { version = "1.27.0", features = ["full"] }
thiserror = "1.0.40"
