[package]
name = "lant"
version = "0.1.0"
edition = "2021"
authors = ["eyeori@icloud.com"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
base64 = "0.21.7"
bytes = "1.5.0"
chrono = "0.4.31"
futures = "0.3.30"
getset = "0.1.2"
net2 = "0.2.39"
once_cell = "1.19.0"
path-absolutize = "3.1.1"
quinn = "0.10.2"
rcgen = "0.12.0"
rustls = { version = "0.21.10", features = ["quic"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
structopt = { version = "0.3.26", features = ["paw"] }
tokio = { version = "1.35.1", features = ["full"] }
thiserror = "1.0.56"
