[package]
name = "lant"
version = "0.1.0"
edition = "2021"
authors = ["eyeori@icloud.com"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
base64 = "0.21.1"
bytes = "1.4.0"
chrono = "0.4.24"
crossbeam-channel = "0.5.8"
futures = "0.3.28"
getset = "0.1.2"
net2 = "0.2.38"
once_cell = "1.17.1"
path-absolutize = "3.1.0"
quinn = "0.10.1"
rcgen = "0.10.0"
rustls = { version = "0.21.1", features = ["quic"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
structopt = { version = "0.3.26", features = ["paw"] }
tokio = { version = "1.28.1", features = ["full"] }
thiserror = "1.0.40"
