[package]
name = "lant"
version = "0.1.0"
edition = "2021"
authors = ["eyeori@icloud.com"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
base64 = "0.21.0"
bytes = "1.3.0"
chrono = "0.4.23"
crossbeam-channel = "0.5.6"
futures = "0.3.25"
getset = "0.1.2"
net2 = "0.2.38"
once_cell = "1.17.0"
path-absolutize = "3.0.14"
quinn = "0.9.3"
rcgen = "0.10.0"
rustls = { version = "0.20.7", features = ["quic"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
structopt = { version = "0.3.26", features = ["paw"] }
tokio = { version = "1.24.2", features = ["full"] }
thiserror = "1.0.38"
