pub const SERVER_NAME: &str = "localhost";

pub const LTS_KEY: &str = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgeL\
    Twygk5W3vWeBfAIJU2qGj/zQIZwKEW7csU7H/lH3ahRANCAAQF\
    /k2hwt0bIjMdrQOi4My5DNjZQUQFULqZzBJrCkm881bCPW9lFh\
    ymsDG7VeGl1U71dTTh1ZYi+6SFZOg69F3n";

pub const LTS_CERT: &str = "MIIBUTCB+KADAgECAghuBHCyWBbhNTAKBggqhkjOPQQDAjAhMR\
    8wHQYDVQQDDBZyY2dlbiBzZWxmIHNpZ25lZCBjZXJ0MCAXDTc1\
    MDEwMTAwMDAwMFoYDzQwOTYwMTAxMDAwMDAwWjAhMR8wHQYDVQ\
    QDDBZyY2dlbiBzZWxmIHNpZ25lZCBjZXJ0MFkwEwYHKoZIzj0C\
    AQYIKoZIzj0DAQcDQgAEBf5NocLdGyIzHa0DouDMuQzY2UFEBV\
    C6mcwSawpJvPNWwj1vZRYcprAxu1XhpdVO9XU04dWWIvukhWTo\
    OvRd56MYMBYwFAYDVR0RBA0wC4IJbG9jYWxob3N0MAoGCCqGSM\
    49BAMCA0gAMEUCIG4ajRSdkqY7ypniXihNToVdPoKKQ2QR2Gjy\
    Kuk0CAg+AiEAg+hGW6NsgAB17HDSu+70ZVmktWUmLc4oE4AJ+j\
    4hLQU=";
